"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { useDatasetStore } from "@/stores/dataset-store";
import { useCanvasStore } from "@/stores/canvas-store";
import { useSettingsStore } from "@/stores/settings-store";
import { MosaicProvider, useMosaic } from "@/components/providers/mosaic-provider";
import { ChartCanvas } from "@/components/canvas/chart-canvas";
import { SchemaPanel } from "@/components/data/schema-panel";
import { DataTable } from "@/components/data/data-table";
import { AISidebar } from "@/components/sidebar/ai-sidebar";
import { serializeProfile } from "@/lib/ai/schema-serializer";
import { parseChartInstructions } from "@/lib/ai/response-parser";
import { SYSTEM_PROMPT, buildAutoGeneratePrompt } from "@/lib/ai/prompts";
import { streamChat } from "@/lib/ai/client";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Database,
  Sparkles,
  MessageSquare,
  Settings,
  ArrowLeft,
  Loader2,
} from "lucide-react";
import Link from "next/link";

function ExploreContent() {
  const router = useRouter();
  const profile = useDatasetStore((s) => s.profile);
  const charts = useCanvasStore((s) => s.charts);
  const setCharts = useCanvasStore((s) => s.setCharts);
  const isGenerating = useCanvasStore((s) => s.isGenerating);
  const setGenerating = useCanvasStore((s) => s.setGenerating);
  const settings = useSettingsStore();
  const { ready: mosaicReady } = useMosaic();

  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [contextChartId, setContextChartId] = useState<string>();
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Redirect if no data loaded
  useEffect(() => {
    if (!profile) {
      router.push("/");
    }
  }, [profile, router]);

  // Load settings from storage
  useEffect(() => {
    settings.loadFromStorage();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-generate charts when data + LLM ready
  const autoGenerate = useCallback(async () => {
    if (!profile || !settings.isConfigured() || autoGenerated || !mosaicReady)
      return;

    setAutoGenerated(true);
    setGenerating(true);

    try {
      const schemaText = serializeProfile(profile);
      const prompt = buildAutoGeneratePrompt(schemaText, profile.tableName);

      const fullText = await streamChat(
        [{ role: "user", content: prompt }],
        SYSTEM_PROMPT,
        {
          baseUrl: settings.apiBaseUrl,
          token: settings.authToken,
          model: settings.modelName,
        },
        () => {} // no streaming UI needed for auto-gen
      );

      const instructions = parseChartInstructions(fullText);
      if (instructions.length > 0) {
        const cards = instructions.map((instr, i) => ({
          id: instr.id,
          instruction: instr,
          layout: {
            x: (i % 3) * 4,
            y: Math.floor(i / 3) * 4,
            w: 4,
            h: 4,
          },
        }));
        setCharts(cards);
      }
    } catch {
      // silently fail, user can use sidebar
    } finally {
      setGenerating(false);
    }
  }, [profile, settings, autoGenerated, mosaicReady, setCharts, setGenerating]);

  useEffect(() => {
    autoGenerate();
  }, [autoGenerate]);

  const handleRefineChart = useCallback(
    (chartId: string) => {
      setContextChartId(chartId);
      setSidebarOpen(true);
    },
    []
  );

  if (!profile) return null;

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b shrink-0">
        <div className="px-4 py-2.5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/">
              <Button variant="ghost" size="icon" className="h-8 w-8">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <Database className="h-4 w-4 text-primary" />
            <span className="font-semibold tracking-tight">DataLens</span>
            <Separator orientation="vertical" className="h-5" />
            <span className="text-sm text-muted-foreground">
              {profile.fileName}
            </span>
            <span className="text-xs text-muted-foreground">
              ({profile.rowCount.toLocaleString()} rows)
            </span>
          </div>

          <div className="flex items-center gap-2">
            {isGenerating && (
              <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Generating...
              </div>
            )}
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                setContextChartId(undefined);
                setSidebarOpen(true);
              }}
            >
              <MessageSquare className="h-3.5 w-3.5 mr-1.5" />
              AI Chat
            </Button>
            {!settings.isConfigured() && (
              <Link href="/settings">
                <Button variant="outline" size="sm">
                  <Settings className="h-3.5 w-3.5 mr-1.5" />
                  Configure LLM
                </Button>
              </Link>
            )}
          </div>
        </div>
      </header>

      {/* Body */}
      <div className="flex-1 flex min-h-0">
        {/* Left sidebar: schema */}
        <aside className="w-72 border-r p-4 shrink-0 hidden lg:block overflow-y-auto">
          <SchemaPanel profile={profile} />
        </aside>

        {/* Main content */}
        <main className="flex-1 min-w-0">
          <Tabs defaultValue="canvas" className="h-full flex flex-col">
            <div className="border-b px-4">
              <TabsList className="h-9">
                <TabsTrigger value="canvas" className="text-xs">
                  <Sparkles className="h-3 w-3 mr-1.5" />
                  Canvas
                </TabsTrigger>
                <TabsTrigger value="data" className="text-xs">
                  <Database className="h-3 w-3 mr-1.5" />
                  Data Table
                </TabsTrigger>
              </TabsList>
            </div>

            <TabsContent value="canvas" className="flex-1 m-0 overflow-auto">
              <ChartCanvas onRefineChart={handleRefineChart} />
            </TabsContent>

            <TabsContent value="data" className="flex-1 m-0 overflow-auto p-4">
              <DataTable
                tableName={profile.tableName}
                columns={profile.columns.map((c) => c.name)}
              />
            </TabsContent>
          </Tabs>
        </main>
      </div>

      {/* AI Sidebar */}
      <AISidebar
        open={sidebarOpen}
        onOpenChange={setSidebarOpen}
        contextChartId={contextChartId}
      />
    </div>
  );
}

export default function ExplorePage() {
  return (
    <MosaicProvider>
      <ExploreContent />
    </MosaicProvider>
  );
}
